Ext.define('Hresource.hresource.shared.com.hresource.model.humanresourceboundedcontext.employee.EmployeeDTOModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "title"
     }, {
          "name": "firstName"
     }, {
          "name": "lastname"
     }, {
          "name": "gender"
     }, {
          "name": "timezone"
     }, {
          "name": "phno"
     }, {
          "name": "emailid"
     }, {
          "name": "addressType"
     }, {
          "name": "country"
     }, {
          "name": "state"
     }, {
          "name": "city"
     }, {
          "name": "zipcode"
     }, {
          "name": "address1"
     }, {
          "name": "address2"
     }, {
          "name": "dob"
     }, {
          "name": "comGrp"
     }, {
          "name": "comType"
     }, {
          "name": "comData"
     }, {
          "name": "depttype"
     }, {
          "name": "desgType"
     }, {
          "name": "reportofficer"
     }, {
          "name": "jobtype"
     }, {
          "name": "pan"
     }, {
          "name": "contactId"
     }]
});