Ext.define('Hresource.hresource.shared.com.hresource.model.humanresourceboundedcontext.attendance.AttendanceSummaryModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "attendenceSummaryId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "maternityLeave",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "empid",
          "reference": "EmployeeInfo",
          "defaultValue": ""
     }, {
          "name": "monthValue",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "yearValue",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "present",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "absent",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "privilegeLeave",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "casualLeave",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "sickLeave",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});