Ext.define('Hresource.hresource.shared.com.hresource.model.humanresourceboundedcontext.payroll.CostToCompanyModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "salaryId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "perk",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "totalCTC",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "takeHome",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "yearValue",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "basic",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "hra",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "convenceAllowance",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "medicalAllowance",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "educationalAllowance",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "specialAllowance",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "empid",
          "reference": "EmployeeInfo",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});